data:
  video_path1: "data/preprocessed/Cropped_Face3_DEAP_s.pkl"
  video_path2: "data/preprocessed/Cropped_Face4_DEAP_s.pkl"
  labels_p_path: "data/preprocessed/Cleaned_Labels_P.pkl"
  labels_a_path: "data/preprocessed/Cleaned_Labels_A.pkl"
  labels_d_path: "data/preprocessed/Cleaned_Labels_D.pkl"

training:
  batch_size: 8
  num_epochs: 40
  learning_rate: 0.001
  sequence_length: 16
  train_split: 0.9
  val_split: 0.8
  patience: 5
  model_save_path: "best_video_model_deap.pth"
